### ISSUE TITLE
Error in ffprobe3 module

### ISSUE THREAD

**Issue by dta9191** [dta9191/VideoCodecRename#15]
When trying to run against directory full of video project folders, get the following error. Seems to be a problem with certain files. Suspected files contain the extension ".mp4.pfl"

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/dustin/Documents/Projects/CodecRenameUtility/JUNK.py", line 153, in add_pressed
    metadata = FFProbe(str(current))
  File "/usr/local/lib/python3.6/dist-packages/ffprobe3/ffprobe.py", line 47, in __init__
    self.streams.append(FFStream(data_lines))
  File "/usr/local/lib/python3.6/dist-packages/ffprobe3/ffprobe.py", line 78, in __init__
    (key, val) = a.strip().split('=')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dta9191** [comment]
Found that the suspected ".mp4.pfl" extension isn't the cause. At least not the only cause. Looking for the offending file.

**Comment by dta9191** [comment]
Was able to call out the offending file using the following code, added to the def add_pressed(event): section.

        except:
            VideoCodecCounts['error'] += 1
            output_box.insert("1.0", "**ERROR: " + str(current))
            output_box.insert(1.0, "\n")
            rename(current, current[0:-4] + '[ERROR]' + current[-4:])
            output_box.insert("1.0", '**Offending File Marked')
            output_box.insert(1.0, "\n")
            pass 

Not sure what is wrong with this video file, but I was able to get through all of the files in the directory after adding in the error handling code I wrote in the very first version.  This seems to be fixed with the addition of basic error handling. I forgot to put the error handling code back into the new version.
